<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('courses')->delete();
        
        \DB::table('courses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'institute_id' => 2,
                'title' => 'Full Stack Web Development',
                'description' => 'Complete web development course covering frontend and backend technologies',
                'duration' => '6 months',
                'category_id' => 1,
                'tagged_skills' => 'HTML, CSS, JavaScript, React, Node.js, MongoDB',
                'batch_limit' => 30,
                'status' => 'active',
                'instructor_name' => 'Dr. Rajesh Kumar',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Introduction to Web Development',
                'module_description' => 'Basics of HTML, CSS, and JavaScript',
                'media' => 'https://example.com/course-banner.jpg',
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2025-10-24 14:55:44',
                'fee' => '45000.00',
                'admin_action' => 'approved',
            ),
            1 => 
            array (
                'id' => 2,
                'institute_id' => 2,
                'title' => 'Data Science with Python',
                'description' => 'Comprehensive data science course including Python, pandas, scikit-learn, and machine learning',
                'duration' => '4 months',
                'category_id' => 1,
                'tagged_skills' => 'Python, Pandas, NumPy, Scikit-learn, Machine Learning',
                'batch_limit' => 25,
                'status' => 'active',
                'instructor_name' => 'Prof. Sunita Sharma',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Python Fundamentals',
                'module_description' => 'Introduction to Python programming',
                'media' => 'https://example.com/datascience.jpg',
                'created_at' => '2024-01-20 11:00:00',
                'updated_at' => '2025-10-24 14:55:37',
                'fee' => '35000.00',
                'admin_action' => 'approved',
            ),
            2 => 
            array (
                'id' => 3,
                'institute_id' => 2,
                'title' => 'Java Enterprise Development',
                'description' => 'Advanced Java programming with Spring Boot and microservices',
                'duration' => '6 months',
                'category_id' => 1,
                'tagged_skills' => 'Java, Spring Boot, Microservices, AWS, Docker',
                'batch_limit' => 20,
                'status' => 'active',
                'instructor_name' => 'Prof. Vikram Singh',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Core Java',
                'module_description' => 'Object-oriented programming concepts',
                'media' => 'https://example.com/java.jpg',
                'created_at' => '2024-01-25 12:00:00',
                'updated_at' => '2025-10-24 14:55:32',
                'fee' => '42000.00',
                'admin_action' => 'approved',
            ),
            3 => 
            array (
                'id' => 4,
                'institute_id' => 2,
                'title' => 'Cloud Computing with AWS',
                'description' => 'Learn AWS services, deployment, and cloud architecture',
                'duration' => '3 months',
                'category_id' => 1,
                'tagged_skills' => 'AWS, Docker, Kubernetes, Jenkins, Linux',
                'batch_limit' => 15,
                'status' => 'active',
                'instructor_name' => 'Anjali Verma',
                'mode' => 'online',
                'certification_allowed' => 1,
                'module_title' => 'AWS Fundamentals',
                'module_description' => 'Introduction to cloud computing',
                'media' => 'https://example.com/aws.jpg',
                'created_at' => '2024-02-01 13:00:00',
                'updated_at' => '2025-10-24 14:55:37',
                'fee' => '30000.00',
                'admin_action' => 'approved',
            ),
            4 => 
            array (
                'id' => 5,
                'institute_id' => 2,
                'title' => 'React Native Mobile Development',
                'description' => 'Build cross-platform mobile apps using React Native',
                'duration' => '4 months',
                'category_id' => 1,
                'tagged_skills' => 'React Native, JavaScript, Mobile Development',
                'batch_limit' => 20,
                'status' => 'active',
                'instructor_name' => 'Ravi Krishnan',
                'mode' => 'hybrid',
                'certification_allowed' => 1,
                'module_title' => 'Mobile App Basics',
                'module_description' => 'Introduction to mobile development',
                'media' => 'https://example.com/reactnative.jpg',
                'created_at' => '2024-02-05 14:00:00',
                'updated_at' => '2025-10-24 14:55:32',
                'fee' => '38000.00',
                'admin_action' => 'approved',
            ),
            5 => 
            array (
                'id' => 6,
                'institute_id' => 2,
                'title' => 'DevOps Engineering',
                'description' => 'Complete DevOps pipeline including Docker, Kubernetes, and CI/CD',
                'duration' => '5 months',
                'category_id' => 1,
                'tagged_skills' => 'Docker, Kubernetes, Jenkins, CI/CD, Linux',
                'batch_limit' => 18,
                'status' => 'active',
                'instructor_name' => 'Meera Nair',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'DevOps Fundamentals',
                'module_description' => 'Introduction to DevOps practices',
                'media' => 'https://example.com/devops.jpg',
                'created_at' => '2024-02-10 15:00:00',
                'updated_at' => '2025-10-24 14:55:37',
                'fee' => '42000.00',
                'admin_action' => 'approved',
            ),
            6 => 
            array (
                'id' => 7,
                'institute_id' => 2,
                'title' => 'UI/UX Design',
                'description' => 'Complete UI/UX design course with modern tools and techniques',
                'duration' => '3 months',
                'category_id' => 2,
                'tagged_skills' => 'Figma, Adobe XD, Photoshop, User Research',
                'batch_limit' => 25,
                'status' => 'active',
                'instructor_name' => 'Pooja Dhameja',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Design Fundamentals',
                'module_description' => 'Introduction to design principles',
                'media' => 'https://example.com/uiux.jpg',
                'created_at' => '2024-02-15 16:00:00',
                'updated_at' => '2025-10-24 14:55:51',
                'fee' => '25000.00',
                'admin_action' => 'approved',
            ),
            7 => 
            array (
                'id' => 8,
                'institute_id' => 2,
                'title' => 'Digital Marketing',
                'description' => 'Complete digital marketing course covering SEO, SEM, and social media',
                'duration' => '4 months',
                'category_id' => 2,
                'tagged_skills' => 'SEO, Google Ads, Social Media, Analytics',
                'batch_limit' => 30,
                'status' => 'active',
                'instructor_name' => 'Neha Gupta',
                'mode' => 'online',
                'certification_allowed' => 1,
                'module_title' => 'Marketing Basics',
                'module_description' => 'Introduction to digital marketing',
                'media' => 'https://example.com/digitalmarketing.jpg',
                'created_at' => '2024-02-20 17:00:00',
                'updated_at' => '2025-10-24 14:55:56',
                'fee' => '20000.00',
                'admin_action' => 'approved',
            ),
            8 => 
            array (
                'id' => 9,
                'institute_id' => 2,
                'title' => 'Cybersecurity Fundamentals',
                'description' => 'Learn cybersecurity concepts and best practices',
                'duration' => '3 months',
                'category_id' => 1,
                'tagged_skills' => 'Network Security, Ethical Hacking, Penetration Testing',
                'batch_limit' => 20,
                'status' => 'active',
                'instructor_name' => 'Arjun Reddy',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Security Basics',
                'module_description' => 'Introduction to cybersecurity',
                'media' => 'https://example.com/cybersecurity.jpg',
                'created_at' => '2024-02-25 18:00:00',
                'updated_at' => '2025-10-24 14:55:56',
                'fee' => '35000.00',
                'admin_action' => 'approved',
            ),
            9 => 
            array (
                'id' => 10,
                'institute_id' => 2,
                'title' => 'Machine Learning with Python',
                'description' => 'Advanced machine learning course with real-world projects',
                'duration' => '5 months',
                'category_id' => 1,
                'tagged_skills' => 'Python, TensorFlow, PyTorch, Deep Learning',
                'batch_limit' => 15,
                'status' => 'active',
                'instructor_name' => 'Kavya Patel',
                'mode' => 'hybrid',
                'certification_allowed' => 1,
                'module_title' => 'ML Fundamentals',
                'module_description' => 'Introduction to machine learning',
                'media' => 'https://example.com/machinelearning.jpg',
                'created_at' => '2024-03-01 19:00:00',
                'updated_at' => '2025-10-24 14:55:56',
                'fee' => '50000.00',
                'admin_action' => 'approved',
            ),
            10 => 
            array (
                'id' => 11,
                'institute_id' => 2,
                'title' => 'Blockchain Development',
                'description' => 'Learn blockchain technology and smart contract development',
                'duration' => '4 months',
                'category_id' => 1,
                'tagged_skills' => 'Solidity, Ethereum, Smart Contracts, Web3',
                'batch_limit' => 12,
                'status' => 'active',
                'instructor_name' => 'Amit Sharma',
                'mode' => 'online',
                'certification_allowed' => 1,
                'module_title' => 'Blockchain Basics',
                'module_description' => 'Introduction to blockchain technology',
                'media' => 'https://example.com/blockchain.jpg',
                'created_at' => '2024-03-05 20:00:00',
                'updated_at' => '2025-10-24 14:55:56',
                'fee' => '45000.00',
                'admin_action' => 'approved',
            ),
            11 => 
            array (
                'id' => 12,
                'institute_id' => 2,
                'title' => 'Game Development',
                'description' => 'Learn game development using Unity and C#',
                'duration' => '6 months',
                'category_id' => 1,
                'tagged_skills' => 'Unity, C#, Game Design, 3D Modeling',
                'batch_limit' => 18,
                'status' => 'active',
                'instructor_name' => 'John Doe',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Game Design Basics',
                'module_description' => 'Introduction to game development',
                'media' => 'https://example.com/gamedev.jpg',
                'created_at' => '2024-03-10 21:00:00',
                'updated_at' => '2025-10-24 14:55:56',
                'fee' => '40000.00',
                'admin_action' => 'approved',
            ),
            12 => 
            array (
                'id' => 13,
                'institute_id' => 2,
                'title' => 'IoT Development',
                'description' => 'Internet of Things development with Arduino and Raspberry Pi',
                'duration' => '4 months',
                'category_id' => 1,
                'tagged_skills' => 'Arduino, Raspberry Pi, Sensors, IoT Protocols',
                'batch_limit' => 15,
                'status' => 'active',
                'instructor_name' => 'Sarah Wilson',
                'mode' => 'hybrid',
                'certification_allowed' => 1,
                'module_title' => 'IoT Fundamentals',
                'module_description' => 'Introduction to IoT concepts',
                'media' => 'https://example.com/iot.jpg',
                'created_at' => '2024-03-15 22:00:00',
                'updated_at' => '2025-10-24 14:55:56',
                'fee' => '30000.00',
                'admin_action' => 'approved',
            ),
            13 => 
            array (
                'id' => 14,
                'institute_id' => 2,
                'title' => 'AR/VR Development',
                'description' => 'Augmented and Virtual Reality development',
                'duration' => '5 months',
                'category_id' => 1,
                'tagged_skills' => 'Unity, ARCore, ARKit, VR Development',
                'batch_limit' => 12,
                'status' => 'active',
                'instructor_name' => 'Mike Johnson',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'AR/VR Basics',
                'module_description' => 'Introduction to AR/VR development',
                'media' => 'https://example.com/arvr.jpg',
                'created_at' => '2024-03-20 23:00:00',
                'updated_at' => '2025-10-24 14:55:56',
                'fee' => '55000.00',
                'admin_action' => 'approved',
            ),
            14 => 
            array (
                'id' => 15,
                'institute_id' => 2,
                'title' => 'Project Management',
                'description' => 'Professional project management course with PMP certification',
                'duration' => '3 months',
                'category_id' => 3,
                'tagged_skills' => 'Agile, Scrum, Project Planning, Risk Management',
                'batch_limit' => 25,
                'status' => 'active',
                'instructor_name' => 'Lisa Brown',
                'mode' => 'online',
                'certification_allowed' => 1,
                'module_title' => 'PM Fundamentals',
                'module_description' => 'Introduction to project management',
                'media' => 'https://example.com/projectmanagement.jpg',
                'created_at' => '2024-03-25 00:00:00',
                'updated_at' => '2025-10-24 14:55:56',
                'fee' => '25000.00',
                'admin_action' => 'approved',
            ),
        ));
        
        
    }
}