<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JobsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('jobs')->delete();
        
        \DB::table('jobs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'recruiter_id' => 1,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Senior Software Engineer',
                'description' => 'We are looking for a senior software engineer with expertise in backend development and system design.',
                'location' => 'Noida, India',
                'skills_required' => 'Java, Spring Boot, Microservices, AWS, Docker',
                'salary_min' => '800000.00',
                'salary_max' => '999999.99',
                'job_type' => 'full_time',
                'experience_required' => '3-5 years',
                'application_deadline' => '2025-09-30 23:59:59',
                'is_remote' => 0,
                'no_of_vacancies' => 2,
                'status' => 'open',
                'is_featured' => 1,
                'save_status' => 1,
                'saved_by_student_id' => NULL,
                'created_at' => '2024-08-01 10:00:00',
                'updated_at' => NULL,
                'admin_action' => 'approved',
            ),
            1 => 
            array (
                'id' => 2,
                'recruiter_id' => 2,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Frontend Developer',
                'description' => 'Join our team as a frontend developer to build amazing user experiences.',
                'location' => 'Bangalore, India',
                'skills_required' => 'React, JavaScript, TypeScript, CSS, HTML',
                'salary_min' => '600000.00',
                'salary_max' => '900000.00',
                'job_type' => 'full_time',
                'experience_required' => '2-4 years',
                'application_deadline' => '2025-09-15 23:59:59',
                'is_remote' => 0,
                'no_of_vacancies' => 3,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 1,
                'saved_by_student_id' => NULL,
                'created_at' => '2024-08-02 11:00:00',
                'updated_at' => NULL,
                'admin_action' => 'approved',
            ),
            2 => 
            array (
                'id' => 3,
                'recruiter_id' => 3,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Data Scientist',
                'description' => 'Looking for a data scientist to work on machine learning models and analytics.',
                'location' => 'Hyderabad, India',
                'skills_required' => 'Python, Machine Learning, TensorFlow, SQL, Statistics',
                'salary_min' => '900000.00',
                'salary_max' => '999999.99',
                'job_type' => 'full_time',
                'experience_required' => '2-5 years',
                'application_deadline' => '2025-10-15 23:59:59',
                'is_remote' => 0,
                'no_of_vacancies' => 1,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2024-08-03 12:00:00',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
            3 => 
            array (
                'id' => 4,
                'recruiter_id' => 1,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'DevOps Engineer',
                'description' => 'DevOps engineer position for managing CI/CD pipelines and infrastructure.',
                'location' => 'Noida, India',
                'skills_required' => 'AWS, Docker, Kubernetes, Jenkins, Linux',
                'salary_min' => '700000.00',
                'salary_max' => '999999.99',
                'job_type' => 'full_time',
                'experience_required' => '2-4 years',
                'application_deadline' => '2025-09-20 23:59:59',
                'is_remote' => 0,
                'no_of_vacancies' => 2,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2024-08-04 13:00:00',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
            4 => 
            array (
                'id' => 5,
                'recruiter_id' => 2,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Senior PHP Developer',
                'description' => 'Work on backend APIs and microservices',
                'location' => 'Remote',
                'skills_required' => 'PHP, MySQL, JWT, REST API',
                'salary_min' => '50000.00',
                'salary_max' => '90000.00',
                'job_type' => 'full_time',
                'experience_required' => '3+ years',
                'application_deadline' => '2025-09-30 00:00:00',
                'is_remote' => 1,
                'no_of_vacancies' => 2,
                'status' => 'closed',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2024-08-05 14:00:00',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
            5 => 
            array (
                'id' => 6,
                'recruiter_id' => 3,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Digital Marketing Specialist',
                'description' => 'Digital marketing role focusing on SEO, SEM, and social media marketing.',
                'location' => 'Hyderabad, India',
                'skills_required' => 'Digital Marketing, SEO, Google Ads, Social Media, Analytics',
                'salary_min' => '400000.00',
                'salary_max' => '700000.00',
                'job_type' => 'full_time',
                'experience_required' => '1-3 years',
                'application_deadline' => '2025-10-01 23:59:59',
                'is_remote' => 1,
                'no_of_vacancies' => 1,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2024-08-06 15:00:00',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
            6 => 
            array (
                'id' => 7,
                'recruiter_id' => 1,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Software Development Intern',
                'description' => 'Internship opportunity for computer science students.',
                'location' => 'Noida, India',
                'skills_required' => 'Java, Python, Web Development, Database',
                'salary_min' => '15000.00',
                'salary_max' => '25000.00',
                'job_type' => 'internship',
                'experience_required' => '0-1 years',
                'application_deadline' => '2025-08-31 23:59:59',
                'is_remote' => 1,
                'no_of_vacancies' => 5,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2024-08-07 16:00:00',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
            7 => 
            array (
                'id' => 9,
                'recruiter_id' => NULL,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Frontend Developer',
                'description' => 'React developer needed',
                'location' => 'Remote',
                'skills_required' => 'React, JS, CSS, HTML',
                'salary_min' => '50000.00',
                'salary_max' => '80000.00',
                'job_type' => 'full_time',
                'experience_required' => '2+ years',
                'application_deadline' => '2025-12-31 00:00:00',
                'is_remote' => 1,
                'no_of_vacancies' => 2,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2025-09-01 13:21:17',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
            8 => 
            array (
                'id' => 11,
                'recruiter_id' => NULL,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Frontend Developer',
                'description' => 'React developer needed',
                'location' => 'Remote',
                'skills_required' => 'React, JS, CSS, HTML',
                'salary_min' => '50000.00',
                'salary_max' => '80000.00',
                'job_type' => 'full_time',
                'experience_required' => '2+ years',
                'application_deadline' => '2025-12-31 00:00:00',
                'is_remote' => 1,
                'no_of_vacancies' => 2,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2025-09-01 13:23:27',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
            9 => 
            array (
                'id' => 12,
                'recruiter_id' => NULL,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Frontend Developer',
                'description' => 'React developer needed',
                'location' => 'Remote',
                'skills_required' => 'React, JS, CSS, HTML',
                'salary_min' => '50000.00',
                'salary_max' => '80000.00',
                'job_type' => 'full_time',
                'experience_required' => '2+ years',
                'application_deadline' => '2025-12-31 00:00:00',
                'is_remote' => 1,
                'no_of_vacancies' => 2,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2025-09-01 13:24:04',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
            10 => 
            array (
                'id' => 13,
                'recruiter_id' => NULL,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Full Stack Developer',
                'description' => 'We are looking for a skilled developer.',
                'location' => 'Bangalore',
                'skills_required' => 'PHP, MySQL, React, Node.js',
                'salary_min' => '50000.00',
                'salary_max' => '80000.00',
                'job_type' => 'full_time',
                'experience_required' => '2-4 years',
                'application_deadline' => '2025-12-31 00:00:00',
                'is_remote' => 1,
                'no_of_vacancies' => 3,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2025-09-25 18:27:55',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
            11 => 
            array (
                'id' => 15,
                'recruiter_id' => 4,
                'company_info_id' => NULL,
                'category_id' => NULL,
                'title' => 'Full Stack Developer',
                'description' => 'We are looking for a skilled developer.',
                'location' => 'Bangalore',
                'skills_required' => 'PHP, MySQL, React, Node.js',
                'salary_min' => '50000.00',
                'salary_max' => '80000.00',
                'job_type' => 'full_time',
                'experience_required' => '2-4 years',
                'application_deadline' => '2025-12-31 00:00:00',
                'is_remote' => 1,
                'no_of_vacancies' => 3,
                'status' => 'open',
                'is_featured' => 0,
                'save_status' => 0,
                'saved_by_student_id' => NULL,
                'created_at' => '2025-09-25 18:34:51',
                'updated_at' => NULL,
                'admin_action' => 'pending',
            ),
        ));
        
        
    }
}