<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StudentProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('student_profiles')->delete();
        
        \DB::table('student_profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 4,
                'skills' => 'JavaScript, React, Node.js, Python, SQL, MongoDB',
            'education' => 'Bachelor of Technology in Computer Science (B.Tech)',
                'resume' => 'uploads/resumes/himanshu_student_resume.pdf',
                'certificates' => 'uploads/certificates/himanshu_certificates.zip',
                'portfolio_link' => 'https://himanshu-portfolio.netlify.app',
                'linkedin_url' => 'https://linkedin.com/in/himanshu-student',
                'dob' => '2000-03-15',
                'gender' => 'male',
                'job_type' => 'full_time',
                'trade' => 'Software Development',
                'created_at' => '2024-06-01 10:00:00',
                'modified_at' => '2025-10-24 12:05:27',
                'deleted_at' => NULL,
                'admin_action' => 'approved',
                'bio' => 'Passionate software developer with strong foundation in full-stack development. Experienced in building scalable web applications and mobile apps.',
                'experience' => '{"level":"Intermediate","years":"2","details":[{"company":"TechNova Pvt Ltd","role":"Frontend Developer","duration":"Jan 2023 - May 2024","description":"Developed React-based web applications and mobile apps using React Native."},{"company":"Brightorial Tech Solutions","role":"Intern","duration":"Aug 2022 - Dec 2022","description":"Assisted in developing a Node.js backend with MongoDB database."}]}',
                'projects' => '[{"name":"E-Commerce Platform","link":"https://himanshu-ecommerce.netlify.app"},{"name":"Task Management App","link":"https://himanshu-tasks.netlify.app"}]',
                'languages' => 'English, Hindi, Marathi',
                'aadhar_number' => '1234-5678-9012',
                'graduation_year' => 2024,
                'cgpa' => '8.50',
                'latitude' => '19.07600000',
                'longitude' => '72.87770000',
                'location' => 'Mumbai, Maharashtra',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 5,
                'skills' => 'PHP, SQL, JavaScript, HTML, CSS',
            'education' => 'Bachelor of Technology in Computer Science (B.Tech)',
                'resume' => 'uploads/resumes/student_5_resume.pdf',
                'certificates' => 'uploads/certificates/student_5_certificates.zip',
                'portfolio_link' => 'https://portfolio.example.com/student5',
                'linkedin_url' => 'https://linkedin.com/in/student5',
                'dob' => '2000-05-15',
                'gender' => 'female',
                'job_type' => 'full_time',
                'trade' => 'IT',
                'created_at' => '2024-06-01 10:00:00',
                'modified_at' => '2025-10-24 12:05:27',
                'deleted_at' => NULL,
                'admin_action' => 'approved',
                'bio' => 'A passionate software developer focused on building scalable backend systems and modern web applications. Skilled in PHP, React, and SQL.',
                'experience' => '{"level":"Intermediate","years":"2","details":[{"company":"TechNova Pvt Ltd","role":"Backend Developer","duration":"Jan 2023 - May 2024","description":"Developed and maintained PHP-based REST APIs for client applications."},{"company":"Brightorial Tech Solutions","role":"Intern","duration":"Aug 2022 - Dec 2022","description":"Assisted in developing a React-based admin panel with MySQL backend."}]}',
                'projects' => '[{"name":"JobSahi Platform","link":"https://jobsahi.in"}]',
                'languages' => 'English, Hindi',
                'aadhar_number' => '9876-5432-8989',
                'graduation_year' => 2023,
                'cgpa' => '8.70',
                'latitude' => '22.71960000',
                'longitude' => '75.85770000',
                'location' => 'Indore, Madhya Pradesh',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 9,
                'skills' => '',
                'education' => '',
                'resume' => '',
                'certificates' => NULL,
                'portfolio_link' => 'http://portfolio.com',
                'linkedin_url' => 'http://linkedin.com/in/student',
                'dob' => '2000-05-15',
                'gender' => 'female',
                'job_type' => 'full_time',
                'trade' => 'IT',
                'created_at' => '2024-06-03 12:00:00',
                'modified_at' => '2025-10-30 19:01:27',
                'deleted_at' => NULL,
                'admin_action' => 'pending',
                'bio' => 'A passionate software developer focused on building scalable backend systems and modern web applications. Skilled in PHP, React, and SQL.',
                'experience' => NULL,
                'projects' => NULL,
                'languages' => NULL,
                'aadhar_number' => NULL,
                'graduation_year' => NULL,
                'cgpa' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'location' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 10,
                'skills' => 'React, Angular, TypeScript, CSS, UI/UX Design',
            'education' => 'B.Des - NIFT Delhi (2020-2024)',
                'resume' => '/uploads/resumes/kavya_patel_resume.pdf',
                'certificates' => NULL,
                'portfolio_link' => 'https://kavyapatel.design',
                'linkedin_url' => 'https://linkedin.com/in/kavyapatel',
                'dob' => '2002-01-14',
                'gender' => 'female',
                'job_type' => 'full_time',
                'trade' => 'Frontend Development',
                'created_at' => '2024-06-04 13:00:00',
                'modified_at' => '2025-10-30 19:01:19',
                'deleted_at' => NULL,
                'admin_action' => 'pending',
                'bio' => 'A passionate software developer focused on building scalable backend systems and modern web applications. Skilled in PHP, React, and SQL.',
                'experience' => NULL,
                'projects' => NULL,
                'languages' => NULL,
                'aadhar_number' => NULL,
                'graduation_year' => NULL,
                'cgpa' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'location' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 11,
                'skills' => 'PHP, MySQL, React',
                'education' => 'B.Tech in Computer Science',
                'resume' => '/uploads/resumes/student_resume.pdf',
                'certificates' => 'uploads/certificates/approved_certificate.pdf',
                'portfolio_link' => 'https://myportfolio.com',
                'linkedin_url' => 'https://linkedin.com/in/student',
                'dob' => '2000-05-15',
                'gender' => 'female',
                'job_type' => 'internship',
                'trade' => 'Software Development',
                'created_at' => '2024-06-05 14:00:00',
                'modified_at' => '2025-10-30 19:01:25',
                'deleted_at' => NULL,
                'admin_action' => 'pending',
                'bio' => 'A passionate software developer focused on building scalable backend systems and modern web applications. Skilled in PHP, React, and SQL.',
                'experience' => NULL,
                'projects' => NULL,
                'languages' => NULL,
                'aadhar_number' => NULL,
                'graduation_year' => NULL,
                'cgpa' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'location' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 12,
                'skills' => 'Digital Marketing, SEO, Content Writing, Social Media',
            'education' => 'MBA Marketing - Symbiosis Pune (2022-2024)',
                'resume' => '/uploads/resumes/neha_gupta_resume.pdf',
                'certificates' => NULL,
                'portfolio_link' => 'https://nehagupta.marketing',
                'linkedin_url' => 'https://linkedin.com/in/nehagupta',
                'dob' => '1999-12-05',
                'gender' => 'female',
                'job_type' => 'full_time',
                'trade' => 'Digital Marketing',
                'created_at' => '2024-06-06 15:00:00',
                'modified_at' => '2025-10-30 19:01:22',
                'deleted_at' => NULL,
                'admin_action' => 'pending',
                'bio' => ' A passionate software developer focused on building scalable backend systems and modern web applications. Skilled in PHP, React, and SQL.',
                'experience' => NULL,
                'projects' => NULL,
                'languages' => NULL,
                'aadhar_number' => NULL,
                'graduation_year' => NULL,
                'cgpa' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'location' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 48,
                'skills' => 'PHP, MySQL, React',
                'education' => 'B.Tech Computer Science',
                'resume' => 'resume.pdf',
                'certificates' => 'AWS, Azure',
                'portfolio_link' => 'http://myportfolio.com',
                'linkedin_url' => 'http://linkedin.com/in/example',
                'dob' => '1998-05-10',
                'gender' => 'female',
                'job_type' => 'full_time',
                'trade' => 'Software Development',
                'created_at' => '2025-09-25 15:18:23',
                'modified_at' => '2025-10-01 21:00:24',
                'deleted_at' => NULL,
                'admin_action' => 'approved',
                'bio' => 'Passionate developer with 3 years experience',
                'experience' => '3 years',
                'projects' => NULL,
                'languages' => NULL,
                'aadhar_number' => NULL,
                'graduation_year' => 2020,
                'cgpa' => '8.50',
                'latitude' => NULL,
                'longitude' => NULL,
                'location' => NULL,
            ),
            7 => 
            array (
                'id' => 15,
                'user_id' => 51,
                'skills' => ' R, Machine Learning, Deep Learning, TensorFlow, PyTorch, Pandas, NumPy, Scikit-learn, SQL, Power BI, Tableau, Statistics, NLP',
                'education' => 'M.Sc. Data Science - IIT Delhi | B.Sc. Mathematics - St. Stephen\'s College, Delhi',
                'resume' => 'https://resume.io/arjun.pdf',
            'certificates' => 'Google Data Analytics Professional Certificate, IBM Data Science Professional Certificate, Deep Learning Specialization (Coursera), TensorFlow Developer Certificate',
                'portfolio_link' => 'https://arjunreddy-ds.netlify.app',
                'linkedin_url' => 'https://linkedin.com/in/arjun-reddy-datascience',
                'dob' => '2000-09-05',
                'gender' => 'male',
                'job_type' => 'part_time',
                'trade' => 'Data Science & Analytics',
                'created_at' => '2025-10-19 18:46:41',
                'modified_at' => '2025-10-30 19:01:07',
                'deleted_at' => NULL,
                'admin_action' => 'pending',
                'bio' => 'Data science enthusiast with strong mathematical foundation and hands-on experience in machine learning. Completed multiple projects in predictive analytics and NLP. Passionate about deriving insights from data and building intelligent systems. Actively contributing to open-source ML projects.',
                'experience' => '{"level":"intermediate","years":"1.5","details":[{"company":"Fractal Analytics","position":"Data Science Intern","duration":"Jun 2024 - Present","description":"Working on customer churn prediction models for telecom client. Implemented ensemble learning techniques improving accuracy by 15%. Creating interactive dashboards using Power BI."},{"type":"research","company":"IIT Delhi Research Lab","position":"Research Assistant","duration":"Jan 2024 - May 2024","description":"Conducted research on sentiment analysis for regional Indian languages. Published paper in national conference. Developed custom NLP pipeline using BERT."},{"type":"project","company":"Kaggle Competition","position":"Individual Contributor","duration":"Aug 2023 - Nov 2023","description":"Participated in image classification competition. Achieved top 5% ranking using CNN and transfer learning techniques."}]}',
                'projects' => NULL,
                'languages' => NULL,
                'aadhar_number' => NULL,
                'graduation_year' => 2025,
                'cgpa' => '9.40',
                'latitude' => '22.71956870',
                'longitude' => '75.85772580',
                'location' => 'Martand Chowk, Indore City, Indore, Juni Indore Tahsil, Indore, Madhya Pradesh, 452001, India',
            ),
        ));
        
        
    }
}