<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('courses')->delete();
        
        \DB::table('courses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'institute_id' => 1,
                'title' => 'Assistant Electrician',
                'description' => 'Comprehensive training in basic electrical tools and practical wiring skills.',
                'duration' => '12',
                'category_id' => 1,
                'tagged_skills' => 'Wiring, Tools, Safety',
                'batch_limit' => 27,
                'status' => 'active',
                'instructor_name' => 'Rajeev Kumar',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Fundamentals of Electricity',
                'module_description' => 'Learn practical and theoretical aspects of electrical work including wiring, tools, and safety standards.',
                'media' => 'istockphoto-1049775258-1024x1024.jpg',
                'fee' => '4500.00',
                'admin_action' => 'approved',
                'created_at' => '2024-10-29 11:34:39',
                'updated_at' => '2025-10-29 16:34:58',
            ),
            1 => 
            array (
                'id' => 2,
                'institute_id' => 1,
                'title' => 'Assistant Electrician Advanced',
                'description' => 'Extended training in wiring and tools.',
                'duration' => '14',
                'category_id' => 1,
                'tagged_skills' => 'Wiring, Tools, Electricity',
                'batch_limit' => 25,
                'status' => 'active',
                'instructor_name' => 'Rajeev Kumar',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Advanced Fundamentals of Electricity',
                'module_description' => 'Deep dive into practical aspects of wiring and safety.',
                'media' => 'course_6901e365defc82.42537390.jpg',
                'fee' => '4800.00',
                'admin_action' => 'approved',
                'created_at' => '2025-10-29 11:45:36',
                'updated_at' => '2025-10-29 15:46:46',
            ),
            2 => 
            array (
                'id' => 3,
                'institute_id' => 1,
            'title' => 'Web Development Bootcamp (Updated)',
                'description' => 'Updated version including Tailwind CSS, API integration, and deployment lessons.',
                'duration' => '14',
                'category_id' => 1,
                'tagged_skills' => 'HTML, CSS, JavaScript, React, Git, Tailwind, APIs',
                'batch_limit' => 45,
                'status' => 'active',
                'instructor_name' => 'Neha Singh',
                'mode' => 'online',
                'certification_allowed' => 1,
                'module_title' => 'Module 3: Advanced Frontend Development',
                'module_description' => 'Covers React Hooks, Context API, and UI deployment best practices.',
                'media' => '["uploads\\/institute_course_image\\/course_6901e365defc82.42537390.jpg"]',
                'fee' => '8200.00',
                'admin_action' => 'pending',
                'created_at' => '2025-10-29 14:29:40',
                'updated_at' => '2025-10-29 15:54:51',
            ),
            3 => 
            array (
                'id' => 4,
                'institute_id' => 1,
                'title' => 'Electrician Foundation Course',
                'description' => 'Learn the fundamentals of electrical circuits, wiring, and safety procedures for beginners.',
                'duration' => '6',
                'category_id' => 3,
                'tagged_skills' => 'Wiring, Circuit Design, Electrical Safety',
                'batch_limit' => 30,
                'status' => 'active',
                'instructor_name' => 'Amit Verma',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Module 1: Introduction to Electricity',
                'module_description' => 'Explains voltage, current, resistance, and basic circuit building.',
                'media' => '["uploads\\/institute_course_image\\/course_6901ec03121bb4.71595414.jpg","uploads\\/institute_course_image\\/course_6901ec03126dc6.74223366.jpg"]',
                'fee' => '3500.00',
                'admin_action' => 'pending',
                'created_at' => '2025-10-29 14:38:53',
                'updated_at' => '2025-10-29 15:58:20',
            ),
            4 => 
            array (
                'id' => 5,
                'institute_id' => 1,
                'title' => 'Electrician Foundation Course',
                'description' => 'Learn the fundamentals of electrical circuits, wiring, and safety procedures for beginners.',
                'duration' => '6',
                'category_id' => 3,
                'tagged_skills' => 'Wiring, Circuit Design, Electrical Safety',
                'batch_limit' => 30,
                'status' => 'active',
                'instructor_name' => 'Amit Verma',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Module 1: Introduction to Electricity',
                'module_description' => 'Explains voltage, current, resistance, and basic circuit building.',
                'media' => '["uploads\\/institute_course_image\\/course_6901ec03121bb4.71595414.jpg","uploads\\/institute_course_image\\/course_6901ec03126dc6.74223366.jpg"]',
                'fee' => '3500.00',
                'admin_action' => 'pending',
                'created_at' => '2025-10-29 14:39:30',
                'updated_at' => '2025-10-29 15:58:12',
            ),
            5 => 
            array (
                'id' => 6,
                'institute_id' => 1,
                'title' => 'Electrician Foundation Course',
                'description' => 'Learn the fundamentals of electrical circuits, wiring, and safety procedures for beginners.',
                'duration' => '6',
                'category_id' => 3,
                'tagged_skills' => 'Wiring, Circuit Design, Electrical Safety',
                'batch_limit' => 30,
                'status' => 'active',
                'instructor_name' => 'Amit Verma',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Module 1: Introduction to Electricity',
                'module_description' => 'Explains voltage, current, resistance, and basic circuit building.',
                'media' => '["uploads\\/institute_course_image\\/course_6901ec03121bb4.71595414.jpg","uploads\\/institute_course_image\\/course_6901ec03126dc6.74223366.jpg"]',
                'fee' => '3500.00',
                'admin_action' => 'pending',
                'created_at' => '2025-10-29 14:39:55',
                'updated_at' => '2025-10-29 15:58:23',
            ),
            6 => 
            array (
                'id' => 7,
                'institute_id' => 1,
                'title' => 'Electrician Foundation Course',
                'description' => 'Learn the fundamentals of electrical circuits, wiring, and safety procedures for beginners.',
                'duration' => '6',
                'category_id' => 3,
                'tagged_skills' => 'Wiring, Circuit Design, Electrical Safety',
                'batch_limit' => 30,
                'status' => 'active',
                'instructor_name' => 'Amit Verma',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Module 1: Introduction to Electricity',
                'module_description' => 'Explains voltage, current, resistance, and basic circuit building.',
                'media' => '["uploads\\/institute_course_image\\/course_6901ec03126dc6.74223366.jpg"]',
                'fee' => '5000.00',
                'admin_action' => 'pending',
                'created_at' => '2025-10-29 14:46:00',
                'updated_at' => '2025-10-29 15:58:36',
            ),
            7 => 
            array (
                'id' => 8,
                'institute_id' => 1,
                'title' => 'Web Development Bootcamp',
                'description' => 'Learn HTML, CSS, JS, React',
                'duration' => '6',
                'category_id' => 2,
                'tagged_skills' => 'HTML, CSS, JS, React',
                'batch_limit' => 0,
                'status' => 'active',
                'instructor_name' => 'Neha Singh',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Module 1: HTML',
                'module_description' => 'Basics of HTML & CSS',
                'media' => '["uploads\\/institute_course_image\\/course_6901e365defc82.42537390.jpg"]',
                'fee' => '5500.00',
                'admin_action' => 'pending',
                'created_at' => '2025-10-29 15:20:29',
                'updated_at' => '2025-10-29 15:20:29',
            ),
            8 => 
            array (
                'id' => 9,
                'institute_id' => 1,
                'title' => 'Electrician Foundation Course',
                'description' => 'Learn the fundamentals of electrical circuits, wiring, and safety procedures.',
                'duration' => '6',
                'category_id' => 3,
                'tagged_skills' => 'Wiring, Safety, Tools',
                'batch_limit' => 30,
                'status' => 'active',
                'instructor_name' => 'Amit Verma',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Module 1: Basics of Electricity',
                'module_description' => 'Covers voltage, current, resistance, and basic tools handling.',
                'media' => '["uploads\\/institute_course_image\\/course_6901ec03121bb4.71595414.jpg","uploads\\/institute_course_image\\/course_6901ec03126dc6.74223366.jpg"]',
                'fee' => '3500.00',
                'admin_action' => 'pending',
                'created_at' => '2025-10-29 15:50:44',
                'updated_at' => '2025-10-29 15:57:49',
            ),
            9 => 
            array (
                'id' => 10,
                'institute_id' => 1,
                'title' => 'Electrician Foundation Course',
                'description' => 'Learn the fundamentals of electrical circuits, wiring, and safety procedures.',
                'duration' => '6',
                'category_id' => 3,
                'tagged_skills' => 'Wiring, Safety, Tools',
                'batch_limit' => 30,
                'status' => 'active',
                'instructor_name' => 'Amit Verma',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Module 1: Basics of Electricity',
                'module_description' => 'Covers voltage, current, resistance, and basic tools handling.',
                'media' => '["uploads\\/institute_course_image\\/course_6901ec03121bb4.71595414.jpg","uploads\\/institute_course_image\\/course_6901ec03126dc6.74223366.jpg"]',
                'fee' => '3500.00',
                'admin_action' => 'pending',
                'created_at' => '2025-10-29 15:56:54',
                'updated_at' => '2025-10-29 15:57:52',
            ),
            10 => 
            array (
                'id' => 11,
                'institute_id' => 1,
                'title' => 'Web Development Bootcamp',
                'description' => 'Learn HTML, CSS, JS, React',
                'duration' => '6',
                'category_id' => 4,
                'tagged_skills' => 'HTML, CSS, JS, React',
                'batch_limit' => 42,
                'status' => 'inactive',
                'instructor_name' => 'Neha Singh',
                'mode' => 'offline',
                'certification_allowed' => 1,
                'module_title' => 'Module 1: HTML',
                'module_description' => 'Basics of HTML & CSS',
                'media' => ',',
                'fee' => '4500.00',
                'admin_action' => 'pending',
                'created_at' => '2025-10-29 15:57:15',
                'updated_at' => '2025-10-30 00:33:27',
            ),
        ));
        
        
    }
}